### ISSUE TITLE
Blank phenotype fields in mapping file

### ISSUE THREAD

**Issue by Alik-V** [spiros/chronological-map-phenotypes#16]
Hi, thank you for this repository!
I got a question regarding [one of the files](https://github.com/spiros/chronological-map-phenotypes/blob/master/phenotype_categories_mapping.csv) - `phenotype_categories_mapping.csv` contains some blanks in the _phenotype_ column. Do you have an insight why that may be?

![image](https://github.com/spiros/chronological-map-phenotypes/assets/43731270/a37dfab4-2065-48d0-a612-5ce27e2d5f51)

**Comment by spiros** [comment]
Hm let me have a look and get back to you! thanks for spotting!

**Comment by spiros** [comment]
hey thank you for flagging this - i've had a look and all phenotypes are represented in the `phenotype_categories_mapping.csv` file so it does not look like anything is missing ; I've removed the lines with the missing values from the file.

**Comment by Alik-V** [comment]
Hi, thank you for looking into this!

**Comment by spiros** [comment]
no probs, sorry in the delay
